apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  namespace: team-2
  labels:
    io.kompose.service: bitnamighost-mariadb-data
  name: bitnamighost-mariadb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi