apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-data
  namespace: team-2
  labels:
    name: ghost-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi