apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-content
  namespace: team-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: team-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - env:
        - name: SERVER_ADDR
          value: http://hellosvc:80/
        - name: REQUESTS_PER_SECOND
          value: '10'
        image: ghost:4.22.0-alpine
        imagePullPolicy: Always
        name: main
      volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content
      volumes:
      - name: content
        persistentVolumeClaim:
          claimName: blog-content
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: team-1
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
  selector:
    app: blog
  type: LoadBalancer
---